version: "2"

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  apt_packages:
    - optipng
  jobs:
    pre_build:
      - mkdir -p $READTHEDOCS_OUTPUT/html/src
      - cp -r $READTHEDOCS_REPOSITORY_PATH/docs/source/src/raw $READTHEDOCS_OUTPUT/html/src

