C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2.4.0)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapwrf_intrp_value (wrf_intrp_valuef2pywrap,
     & wvalp0, wvalp1, vlev, vcp0, vcp1, icase, errstat)
      external wrf_intrp_value
      real(kind=8) wvalp0
      real(kind=8) wvalp1
      real(kind=8) vlev
      real(kind=8) vcp0
      real(kind=8) vcp1
      integer icase
      integer errstat
      real(kind=8) wrf_intrp_valuef2pywrap
      real(kind=8)  wrf_intrp_value
      wrf_intrp_valuef2pywrap = wrf_intrp_value(wvalp0, wvalp1, vl
     &ev, vcp0, vcp1, icase, errstat)
      end


      subroutine f2pywraptvirtual (tvirtualf2pywrap, temp, ratmix)
      external tvirtual
      real(kind=8) temp
      real(kind=8) ratmix
      real(kind=8) tvirtualf2pywrap
      real(kind=8)  tvirtual
      tvirtualf2pywrap = tvirtual(temp, ratmix)
      end


      subroutine f2pywraptonpsadiabat (tonpsadiabatf2pywrap, thte,
     & prs, psadithte, psadiprs, psaditmk, gamma, errstat, errmsg)
      external tonpsadiabat
      real(kind=8) thte
      real(kind=8) prs
      real(kind=8) gamma
      integer errstat
      real(kind=8) psadithte(150)
      real(kind=8) psadiprs(150)
      real(kind=8) psaditmk(150,150)
      character*(*) errmsg
      real(kind=8) tonpsadiabatf2pywrap
      real(kind=8)  tonpsadiabat
      tonpsadiabatf2pywrap = tonpsadiabat(thte, prs, psadithte, ps
     &adiprs, psaditmk, gamma, errstat, errmsg)
      end


      subroutine f2pywrapfomp_enabled (fomp_enabledf2pywrap)
      external fomp_enabled
      logical fomp_enabledf2pywrap
      logical  fomp_enabled
      fomp_enabledf2pywrap = .not.(.not.fomp_enabled())
      end


      subroutine f2pywrapfomp_get_num_threads (fomp_get_num_thread
     &sf2pywrap)
      external fomp_get_num_threads
      integer fomp_get_num_threadsf2pywrap
      integer  fomp_get_num_threads
      fomp_get_num_threadsf2pywrap = fomp_get_num_threads()
      end


      subroutine f2pywrapfomp_get_max_threads (fomp_get_max_thread
     &sf2pywrap)
      external fomp_get_max_threads
      integer fomp_get_max_threadsf2pywrap
      integer  fomp_get_max_threads
      fomp_get_max_threadsf2pywrap = fomp_get_max_threads()
      end


      subroutine f2pywrapfomp_get_thread_num (fomp_get_thread_numf
     &2pywrap)
      external fomp_get_thread_num
      integer fomp_get_thread_numf2pywrap
      integer  fomp_get_thread_num
      fomp_get_thread_numf2pywrap = fomp_get_thread_num()
      end


      subroutine f2pywrapfomp_get_num_procs (fomp_get_num_procsf2p
     &ywrap)
      external fomp_get_num_procs
      integer fomp_get_num_procsf2pywrap
      integer  fomp_get_num_procs
      fomp_get_num_procsf2pywrap = fomp_get_num_procs()
      end


      subroutine f2pywrapfomp_in_parallel (fomp_in_parallelf2pywra
     &p)
      external fomp_in_parallel
      logical fomp_in_parallelf2pywrap
      logical  fomp_in_parallel
      fomp_in_parallelf2pywrap = .not.(.not.fomp_in_parallel())
      end


      subroutine f2pywrapfomp_get_dynamic (fomp_get_dynamicf2pywra
     &p)
      external fomp_get_dynamic
      logical fomp_get_dynamicf2pywrap
      logical  fomp_get_dynamic
      fomp_get_dynamicf2pywrap = .not.(.not.fomp_get_dynamic())
      end


      subroutine f2pywrapfomp_get_nested (fomp_get_nestedf2pywrap)
      external fomp_get_nested
      logical fomp_get_nestedf2pywrap
      logical  fomp_get_nested
      fomp_get_nestedf2pywrap = .not.(.not.fomp_get_nested())
      end


      subroutine f2pywrapfomp_get_thread_limit (fomp_get_thread_li
     &mitf2pywrap)
      external fomp_get_thread_limit
      integer fomp_get_thread_limitf2pywrap
      integer  fomp_get_thread_limit
      fomp_get_thread_limitf2pywrap = fomp_get_thread_limit()
      end


      subroutine f2pywrapfomp_get_max_active_levels (fomp_get_max_
     &active_levelsf2pywrap)
      external fomp_get_max_active_levels
      integer fomp_get_max_active_levelsf2pywrap
      integer  fomp_get_max_active_levels
      fomp_get_max_active_levelsf2pywrap = fomp_get_max_active_lev
     &els()
      end


      subroutine f2pywrapfomp_get_level (fomp_get_levelf2pywrap)
      external fomp_get_level
      integer fomp_get_levelf2pywrap
      integer  fomp_get_level
      fomp_get_levelf2pywrap = fomp_get_level()
      end


      subroutine f2pywrapfomp_get_ancestor_thread_num (fomp_get_an
     &cestor_thread_numf2pywrap, level)
      external fomp_get_ancestor_thread_num
      integer level
      integer fomp_get_ancestor_thread_numf2pywrap
      integer  fomp_get_ancestor_thread_num
      fomp_get_ancestor_thread_numf2pywrap = fomp_get_ancestor_thr
     &ead_num(level)
      end


      subroutine f2pywrapfomp_get_team_size (fomp_get_team_sizef2p
     &ywrap, level)
      external fomp_get_team_size
      integer level
      integer fomp_get_team_sizef2pywrap
      integer  fomp_get_team_size
      fomp_get_team_sizef2pywrap = fomp_get_team_size(level)
      end


      subroutine f2pywrapfomp_get_active_level (fomp_get_active_le
     &velf2pywrap)
      external fomp_get_active_level
      integer fomp_get_active_levelf2pywrap
      integer  fomp_get_active_level
      fomp_get_active_levelf2pywrap = fomp_get_active_level()
      end


      subroutine f2pywrapfomp_in_final (fomp_in_finalf2pywrap)
      external fomp_in_final
      logical fomp_in_finalf2pywrap
      logical  fomp_in_final
      fomp_in_finalf2pywrap = .not.(.not.fomp_in_final())
      end


      subroutine f2pywrapfomp_test_lock (fomp_test_lockf2pywrap, s
     &var)
      external fomp_test_lock
      integer(kind=8) svar
      logical fomp_test_lockf2pywrap
      logical  fomp_test_lock
      fomp_test_lockf2pywrap = .not.(.not.fomp_test_lock(svar))
      end


      subroutine f2pywrapfomp_test_nest_lock (fomp_test_nest_lockf
     &2pywrap, nvar)
      external fomp_test_nest_lock
      integer(kind=8) nvar
      integer fomp_test_nest_lockf2pywrap
      integer  fomp_test_nest_lock
      fomp_test_nest_lockf2pywrap = fomp_test_nest_lock(nvar)
      end


      subroutine f2pywrapfomp_get_wtime (fomp_get_wtimef2pywrap)
      external fomp_get_wtime
      real(kind=8) fomp_get_wtimef2pywrap
      real(kind=8)  fomp_get_wtime
      fomp_get_wtimef2pywrap = fomp_get_wtime()
      end


      subroutine f2pywrapfomp_get_wtick (fomp_get_wtickf2pywrap)
      external fomp_get_wtick
      real(kind=8) fomp_get_wtickf2pywrap
      real(kind=8)  fomp_get_wtick
      fomp_get_wtickf2pywrap = fomp_get_wtick()
      end

