!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2.4.0)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinitwrf_constants(f2pysetupfunc)
      use wrf_constants, only : errlen
      use wrf_constants, only : algerr
      use wrf_constants, only : wrf_earth_radius
      use wrf_constants, only : t_base
      use wrf_constants, only : pi
      use wrf_constants, only : rad_per_deg
      use wrf_constants, only : deg_per_rad
      use wrf_constants, only : default_fill
      use wrf_constants, only : default_fill_int8
      use wrf_constants, only : default_fill_int16
      use wrf_constants, only : default_fill_int32
      use wrf_constants, only : default_fill_int64
      use wrf_constants, only : default_fill_float
      use wrf_constants, only : default_fill_double
      use wrf_constants, only : default_fill_char
      use wrf_constants, only : p1000mb
      use wrf_constants, only : rd
      use wrf_constants, only : rv
      use wrf_constants, only : cp
      use wrf_constants, only : g
      use wrf_constants, only : ussalr
      use wrf_constants, only : celkel
      use wrf_constants, only : celkel_triple
      use wrf_constants, only : ezero
      use wrf_constants, only : eslcon1
      use wrf_constants, only : eslcon2
      use wrf_constants, only : eps
      use wrf_constants, only : gamma
      use wrf_constants, only : cpmd
      use wrf_constants, only : rgasmd
      use wrf_constants, only : gammamd
      use wrf_constants, only : tlclc1
      use wrf_constants, only : tlclc2
      use wrf_constants, only : tlclc3
      use wrf_constants, only : tlclc4
      use wrf_constants, only : thtecon1
      use wrf_constants, only : thtecon2
      use wrf_constants, only : thtecon3
      use wrf_constants, only : abscoefi
      use wrf_constants, only : abscoef
      use wrf_constants, only : gamma_seven
      use wrf_constants, only : rhowat
      use wrf_constants, only : rho_r
      use wrf_constants, only : rho_s
      use wrf_constants, only : rho_g
      use wrf_constants, only : alpha
      use wrf_constants, only : sclht
      use wrf_constants, only : expon
      use wrf_constants, only : exponi
      external f2pysetupfunc
      call f2pysetupfunc(errlen,algerr,wrf_earth_radius,t_base,pi,rad_pe&
     &r_deg,deg_per_rad,default_fill,default_fill_int8,default_fill_int1&
     &6,default_fill_int32,default_fill_int64,default_fill_float,default&
     &_fill_double,default_fill_char,p1000mb,rd,rv,cp,g,ussalr,celkel,ce&
     &lkel_triple,ezero,eslcon1,eslcon2,eps,gamma,cpmd,rgasmd,gammamd,tl&
     &clc1,tlclc2,tlclc3,tlclc4,thtecon1,thtecon2,thtecon3,abscoefi,absc&
     &oef,gamma_seven,rhowat,rho_r,rho_s,rho_g,alpha,sclht,expon,exponi)
      end subroutine f2pyinitwrf_constants


