/* File: _wrf_constantsmodule.c
 * This file is auto-generated with f2py (version:2.4.0).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Tue Dec 30 08:15:19 2025
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
/*need_includes0*/

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *_wrf_constants_error;
static PyObject *_wrf_constants_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
/*need_cfuncs*/

/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/

static FortranDataDef f2py_wrf_constants_def[] = {
  {"errlen",0,{{-1}},NPY_INT, 1},
  {"algerr",0,{{-1}},NPY_INT, 1},
  {"wrf_earth_radius",0,{{-1}},NPY_DOUBLE, 1},
  {"t_base",0,{{-1}},NPY_DOUBLE, 1},
  {"pi",0,{{-1}},NPY_DOUBLE, 1},
  {"rad_per_deg",0,{{-1}},NPY_DOUBLE, 1},
  {"deg_per_rad",0,{{-1}},NPY_DOUBLE, 1},
  {"default_fill",0,{{-1}},NPY_DOUBLE, 1},
  {"default_fill_int8",0,{{-1}},NPY_BYTE, 1},
  {"default_fill_int16",0,{{-1}},NPY_SHORT, 1},
  {"default_fill_int32",0,{{-1}},NPY_INT, 1},
  {"default_fill_int64",0,{{-1}},NPY_LONGLONG, 1},
  {"default_fill_float",0,{{-1}},NPY_FLOAT, 1},
  {"default_fill_double",0,{{-1}},NPY_DOUBLE, 1},
  {"default_fill_char",0,{{-1}},NPY_STRING, 1},
  {"p1000mb",0,{{-1}},NPY_DOUBLE, 1},
  {"rd",0,{{-1}},NPY_DOUBLE, 1},
  {"rv",0,{{-1}},NPY_DOUBLE, 1},
  {"cp",0,{{-1}},NPY_DOUBLE, 1},
  {"g",0,{{-1}},NPY_DOUBLE, 1},
  {"ussalr",0,{{-1}},NPY_DOUBLE, 1},
  {"celkel",0,{{-1}},NPY_DOUBLE, 1},
  {"celkel_triple",0,{{-1}},NPY_DOUBLE, 1},
  {"ezero",0,{{-1}},NPY_DOUBLE, 1},
  {"eslcon1",0,{{-1}},NPY_DOUBLE, 1},
  {"eslcon2",0,{{-1}},NPY_DOUBLE, 1},
  {"eps",0,{{-1}},NPY_DOUBLE, 1},
  {"gamma",0,{{-1}},NPY_DOUBLE, 1},
  {"cpmd",0,{{-1}},NPY_DOUBLE, 1},
  {"rgasmd",0,{{-1}},NPY_DOUBLE, 1},
  {"gammamd",0,{{-1}},NPY_DOUBLE, 1},
  {"tlclc1",0,{{-1}},NPY_DOUBLE, 1},
  {"tlclc2",0,{{-1}},NPY_DOUBLE, 1},
  {"tlclc3",0,{{-1}},NPY_DOUBLE, 1},
  {"tlclc4",0,{{-1}},NPY_DOUBLE, 1},
  {"thtecon1",0,{{-1}},NPY_DOUBLE, 1},
  {"thtecon2",0,{{-1}},NPY_DOUBLE, 1},
  {"thtecon3",0,{{-1}},NPY_DOUBLE, 1},
  {"abscoefi",0,{{-1}},NPY_DOUBLE, 1},
  {"abscoef",0,{{-1}},NPY_DOUBLE, 1},
  {"gamma_seven",0,{{-1}},NPY_DOUBLE, 1},
  {"rhowat",0,{{-1}},NPY_DOUBLE, 1},
  {"rho_r",0,{{-1}},NPY_DOUBLE, 1},
  {"rho_s",0,{{-1}},NPY_DOUBLE, 1},
  {"rho_g",0,{{-1}},NPY_DOUBLE, 1},
  {"alpha",0,{{-1}},NPY_DOUBLE, 1},
  {"sclht",0,{{-1}},NPY_DOUBLE, 1},
  {"expon",0,{{-1}},NPY_DOUBLE, 1},
  {"exponi",0,{{-1}},NPY_DOUBLE, 1},
  {NULL}
};
static void f2py_setup_wrf_constants(char *errlen,char *algerr,char *wrf_earth_radius,char *t_base,char *pi,char *rad_per_deg,char *deg_per_rad,char *default_fill,char *default_fill_int8,char *default_fill_int16,char *default_fill_int32,char *default_fill_int64,char *default_fill_float,char *default_fill_double,char *default_fill_char,char *p1000mb,char *rd,char *rv,char *cp,char *g,char *ussalr,char *celkel,char *celkel_triple,char *ezero,char *eslcon1,char *eslcon2,char *eps,char *gamma,char *cpmd,char *rgasmd,char *gammamd,char *tlclc1,char *tlclc2,char *tlclc3,char *tlclc4,char *thtecon1,char *thtecon2,char *thtecon3,char *abscoefi,char *abscoef,char *gamma_seven,char *rhowat,char *rho_r,char *rho_s,char *rho_g,char *alpha,char *sclht,char *expon,char *exponi) {
  int i_f2py=0;
  f2py_wrf_constants_def[i_f2py++].data = errlen;
  f2py_wrf_constants_def[i_f2py++].data = algerr;
  f2py_wrf_constants_def[i_f2py++].data = wrf_earth_radius;
  f2py_wrf_constants_def[i_f2py++].data = t_base;
  f2py_wrf_constants_def[i_f2py++].data = pi;
  f2py_wrf_constants_def[i_f2py++].data = rad_per_deg;
  f2py_wrf_constants_def[i_f2py++].data = deg_per_rad;
  f2py_wrf_constants_def[i_f2py++].data = default_fill;
  f2py_wrf_constants_def[i_f2py++].data = default_fill_int8;
  f2py_wrf_constants_def[i_f2py++].data = default_fill_int16;
  f2py_wrf_constants_def[i_f2py++].data = default_fill_int32;
  f2py_wrf_constants_def[i_f2py++].data = default_fill_int64;
  f2py_wrf_constants_def[i_f2py++].data = default_fill_float;
  f2py_wrf_constants_def[i_f2py++].data = default_fill_double;
  f2py_wrf_constants_def[i_f2py++].data = default_fill_char;
  f2py_wrf_constants_def[i_f2py++].data = p1000mb;
  f2py_wrf_constants_def[i_f2py++].data = rd;
  f2py_wrf_constants_def[i_f2py++].data = rv;
  f2py_wrf_constants_def[i_f2py++].data = cp;
  f2py_wrf_constants_def[i_f2py++].data = g;
  f2py_wrf_constants_def[i_f2py++].data = ussalr;
  f2py_wrf_constants_def[i_f2py++].data = celkel;
  f2py_wrf_constants_def[i_f2py++].data = celkel_triple;
  f2py_wrf_constants_def[i_f2py++].data = ezero;
  f2py_wrf_constants_def[i_f2py++].data = eslcon1;
  f2py_wrf_constants_def[i_f2py++].data = eslcon2;
  f2py_wrf_constants_def[i_f2py++].data = eps;
  f2py_wrf_constants_def[i_f2py++].data = gamma;
  f2py_wrf_constants_def[i_f2py++].data = cpmd;
  f2py_wrf_constants_def[i_f2py++].data = rgasmd;
  f2py_wrf_constants_def[i_f2py++].data = gammamd;
  f2py_wrf_constants_def[i_f2py++].data = tlclc1;
  f2py_wrf_constants_def[i_f2py++].data = tlclc2;
  f2py_wrf_constants_def[i_f2py++].data = tlclc3;
  f2py_wrf_constants_def[i_f2py++].data = tlclc4;
  f2py_wrf_constants_def[i_f2py++].data = thtecon1;
  f2py_wrf_constants_def[i_f2py++].data = thtecon2;
  f2py_wrf_constants_def[i_f2py++].data = thtecon3;
  f2py_wrf_constants_def[i_f2py++].data = abscoefi;
  f2py_wrf_constants_def[i_f2py++].data = abscoef;
  f2py_wrf_constants_def[i_f2py++].data = gamma_seven;
  f2py_wrf_constants_def[i_f2py++].data = rhowat;
  f2py_wrf_constants_def[i_f2py++].data = rho_r;
  f2py_wrf_constants_def[i_f2py++].data = rho_s;
  f2py_wrf_constants_def[i_f2py++].data = rho_g;
  f2py_wrf_constants_def[i_f2py++].data = alpha;
  f2py_wrf_constants_def[i_f2py++].data = sclht;
  f2py_wrf_constants_def[i_f2py++].data = expon;
  f2py_wrf_constants_def[i_f2py++].data = exponi;
}
extern void F_FUNC_US(f2pyinitwrf_constants,F2PYINITWRF_CONSTANTS)(void (*)(char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*));
static void f2py_init_wrf_constants(void) {
  F_FUNC_US(f2pyinitwrf_constants,F2PYINITWRF_CONSTANTS)(f2py_setup_wrf_constants);
}
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/
/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "_wrf_constants",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit__wrf_constants(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = _wrf_constants_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module _wrf_constants (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("2.4.0");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module '_wrf_constants' is auto-generated with f2py (version:2.4.0).\nFunctions:\n"
"Fortran 90/95 modules:\n""  wrf_constants --- errlen,algerr,wrf_earth_radius,t_base,pi,rad_per_deg,deg_per_rad,default_fill,default_fill_int8,default_fill_int16,default_fill_int32,default_fill_int64,default_fill_float,default_fill_double,default_fill_char,p1000mb,rd,rv,cp,g,ussalr,celkel,celkel_triple,ezero,eslcon1,eslcon2,eps,gamma,cpmd,rgasmd,gammamd,tlclc1,tlclc2,tlclc3,tlclc4,thtecon1,thtecon2,thtecon3,abscoefi,abscoef,gamma_seven,rhowat,rho_r,rho_s,rho_g,alpha,sclht,expon,exponi"".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("2.4.0");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    _wrf_constants_error = PyErr_NewException ("_wrf_constants.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "__wrf_constants_error", _wrf_constants_error);
    Py_DECREF(_wrf_constants_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }
/*eof initf2pywraphooks*/
  PyDict_SetItemString(d, "wrf_constants", PyFortranObject_New(f2py_wrf_constants_def,f2py_init_wrf_constants));/*eof initf90modhooks*/
/*eof initcommonhooks*/


#ifdef Py_GIL_DISABLED
    // signal whether this module supports running with the GIL disabled
    PyUnstable_Module_SetGIL(m , Py_MOD_GIL_USED);
#endif

#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"_wrf_constants");
#endif

    if (PyType_Ready(&PyFortran_Type) < 0) {
        return NULL;
    }

    return m;
}
#ifdef __cplusplus
}
#endif
